"""

    Autogenerated by ghenerate script, part of Quantarhei
    http://github.com/tmancal74/quantarhei
    Tomas Mancal, tmancal74@gmai.com

    Generated on: 2018-06-20 09:59:45

    Edit the functions below to give them desired functionality.
    In present version of `ghenerate`, no edits or replacements
    are perfomed in the feature file text.

"""
import numpy

from behave import given
from behave import when
from behave import then

import quantarhei as qr

##
## Given ...
##
#@given('Given I have a Hamiltonian H, Lidblad form L an initial density matrix R')
#def step_given_1(context):
#    """
#
#        Given Given I have a Hamiltonian H, Lidblad form L an initial density matrix R
#
#    """
#    pass
#

#
# When ...
#
@when('I calculate evolution superoperator U with time step {N_dense} times large than needed for numerics')
def step_when_2(context, N_dense):
    """

        When I calculate evolution superoperator U with time step {N_dense} times large than needed for numerics

    """
    # parameter from outside
    Nd = int(N_dense)
    
    # all that is needed from context
    HH = context.H
    LL = context.L
    time = context.time
    
    # time step and number of steps
    Nt = time.length
    dt = time.step

    # we will make Nd times longer steps
    Nt_u = int(Nt/Nd)
    dt_u = dt*Nd
    
    # new time axis
    time_u = qr.TimeAxis(0.0, Nt_u, dt_u)
    
    # calculate evolution superoperator
    U = qr.qm.EvolutionSuperOperator(time=time_u, ham=HH, relt=LL)
    U.set_dense_dt(Nd)
    U.calculate()
    
    # save into context
    context.U = U


##
## And ...
##
#@when('I calculate dynamics of R using H and L to get R1')
#def step_when_3(context):
#    """
#
#        And I calculate dynamics of R using H and L to get R1
#
#    """
#    pass


##
## And ...
##
#@when('I apply the evolution superoperator to R to get R2 at times {t_prop}')
#def step_when_4(context, t_prop):
#    """
#
#        And I apply the evolution superoperator to R to get R2 at times {t_prop}
#
#    """
#    pass
#

##
## Then ...
##
#@then('R1 equals R2 at times {t_prop}')
#def step_then_5(context, t_prop):
#    """
#
#        Then R1 equals R2 at times {t_prop}
#
#    """
#    pass

#
# And ...
#
@when('I get the evolution super operator S at a single time {t_prop}')
def step_when_6(context, t_prop):
    """

        And I get the evolution super operator S at a single time {t_prop}

    """
    t = float(t_prop)
    U = context.U
    S = U.at(t)
    
    context.S = S


#
# And ...
#
@when('I apply the evolution superoperator S to R to get R3 at times {t_prop}')
def step_when_7(context, t_prop):
    """

        And I apply the evolution superoperator S to R to get R3 at times {t_prop}

    """
    R = context.R
    S = context.S
    
    R3 = S.apply(R)
    
    context.R3 = R3

#
# Then ...
#
@then('R2 equals R3 at times {t_prop}')
def step_then_8(context, t_prop):
    """

        Then R2 equals R3 at times {t_prop}

    """
    t = float(t_prop)
    R3 = context.R3
    R2 = context.R2
    
    numpy.testing.assert_allclose(R3.data, R2.data, rtol=1.0e-12, atol=1.0e-12)