"""

    Autogenerated by ghenerate script, part of Quantarhei
    http://github.com/tmancal74/quantarhei
    Tomas Mancal, tmancal74@gmai.com

    Generated on: 2018-06-04 13:53:49

    Edit the functions below to give them desired functionality.
    In present version of `ghenerate`, no edits or replacements
    are perfomed in the feature file text.

"""

from behave import *


#
# Given ... 
#
@given('that Quantarhei is installed')
def step_given(context):
    pass


#
# When ...
#
@when('I run the ghenerate script')
def step_when(context):
    pass


#
# Then ...
#
@then('I get a simple usage message')
def step_then(context):
    pass


#
# And ...
#
@given('current directory contains a feature file')
def step_given(context):
    pass


#
# And ...
#
@given('the default destination directory exists')
def step_given(context):
    pass


#
# When ...
#
@when('I run the ghenerate script with the name of the feature file')
def step_when(context):
    pass


#
# Then ...
#
@then('feature file is converted into a Python step file')
def step_then(context):
    pass


#
# And ...
#
@then('the step file is saved into default destination directory')
def step_then(context):
    pass


#
# And ...
#
@given('{destination_directory} exists')
def step_given(context, destination_directory):
    pass


#
# When ...
#
@when('I run {ghenerate_command} with the option specifying destination directory')
def step_when(context, ghenerate_command):
    pass


#
# And ...
#
@then('step file is saved into the destination directory')
def step_then(context):
    pass


#
# And ...
#
@given('the {destination_directory} does not exist')
def step_given(context, destination_directory):
    pass


#
# When ...
#
@when('I run {ghenerate_command} with feature file name')
def step_when(context, ghenerate_command):
    pass


#
# Then ...
#
@then('destination directory is created')
def step_then(context):
    pass


#
# And ...
#
@then('step file is saved to the destination directory')
def step_then(context):
    pass
