"""

    Autogenerated by ghenerate script, part of Quantarhei
    http://github.com/tmancal74/quantarhei
    Tomas Mancal, tmancal74@gmai.com
    
    Generated on: 2018-06-02 00:18:15 

    Edit the functions below to give them desired functionality.
    In present version of `ghenerate`, no edits or replacements
    are perfomed in the feature file text.


"""

from behave import *


#
# Given ... 
#
@given('that I have a list of examples from qrhei list')
def step_given(context):
    pass


#
# When ...
#
@when('I fetch all examples one by one')
def step_when(context):
    pass


#
# Then ...
#
@then('examples are all fetchable')
def step_then(context):
    pass
