name: Quantarhei

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_devel.txt
        pip install -e .

    - name: Run unit tests
      run: |
        pytest -v \
          --cov=quantarhei \
          --cov-report=term \
          --cov-report=xml:coverage1.xml \
          tests/unit

    - name: Run doc tests
      run: |
        pytest --doctest-modules -v \
          --cov=quantarhei \
          --cov-append \
          --cov-report=xml:coverage2.xml \
          quantarhei/core \
          quantarhei/builders \
          quantarhei/qm/corfunctions \
          quantarhei/spectroscopy \
          quantarhei/qm/liouvillespace \
          quantarhei/functions \
          quantarhei/qm/hilbertspace \
          quantarhei/qm/propagators \
          quantarhei/qm/propagators/poppropagator.py

    - name: Run behave tests
      run: |
        coverage run $(which behave) tests/behave/features

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
